category: web
title:
  ru: Будильник
  en: Alarm clock
points:   350
author:   purplesyringa
description:
  ru: |
    <p>Наши уважаемые англосаксонские партнеры вот-вот начнут продавать свой Умный Будильник. Мы же,
    заботясь о здоровье людей, пришли к выводу, что это устройство принесет серьезный вред населению
    Земли, который нужно во что бы то ни стало предотвратить.</p>

    <p>Мы заслали в компанию smartAlarm диверсанта, который смог стащить тестовый код доступа к
    веб-интерфейсу Умного Будильника и фотографию его внутрняки.</p>

    <p>Мы предполагаем, что основатель компании может хранить на своем ноутбуке дискредитирующую его
    информацию. Поможете проверить, так ли это?</p>

    <p><small>Сервер этой задачи запущен в отдельном контейнере для вашей команды.</small></p>
    <form method="POST">
        <button>Перезапустить контейнер</button>
    </form>
    <script>
        Array.from(document.querySelectorAll("form")).slice(-1)[0].action = location.protocol + "//pupupu." + location.host + "/__internal__/reboot_container/{{token}}/?" + location.href;
    </script>
  en: |
    <p>Our partners from Great Britain are about to start selling their Smart Alarm. We care about
    people's health and believe this device will cause great harm to humanity. We wish to stop the
    product from being released.</p>

    <p>We have managed to get a hold on someone from smartAlarm, and they managed to steal a test
    access key to the web interface of Smart Alarm. They have also made a photo of the internals of
    the device.</p>

    <p>We believe that the founder of smartAlarm might store some discrediting information on their
    laptop. Help us figure out if that's the case.</p>

    <p><small>The server of this task is running in a container per team.</small></p>
    <form method="POST">
        <button>Restart container</button>
    </form>
    <script>
        Array.from(document.querySelectorAll("form")).slice(-1)[0].action = location.protocol + "//pupupu." + location.host + "/__internal__/reboot_container/{{token}}/?" + location.href;
    </script>
attachments_path: attachments
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: ../_scripts/kyzylborda-lib-quarantine-daemon Dockerfile.controller uid2 uid7
  cwd: .
  socket: ./app.sock
  socket_type: http
secrets:
  seed: RJISvYbEsce6eHkcLez5DbUpzwUAIKke
  flag: ugra_time_to_get_up_[a-z0-9]{12}
# meow1
