[package]
name = "pedersen"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"

[dependencies]
base64 = "0.21.7"
bulletproofs = "4.0.0"
curve25519-dalek-ng = "4.1.1"
hex = "0.4.3"
rand = "0.8.5"
rocket = "0.5.0"
serde = "1.0.196"
serde_json = "1.0.113"

[lib]
name = "crypto"
path = "src/crypto/lib.rs"

[[bin]]
name = "backend"
path = "src/bin/backend.rs"
