FROM docker.io/ocaml/opam:debian-ocaml-5.1

RUN sudo bash -c 'apt-get update && apt-get install -y zip && apt-get clean && rm -rf /var/lib/apt/lists/*'

COPY --chown=opam:opam ./task /treemen

WORKDIR /

COPY ./generate.sh /generate.sh

USER opam
ENTRYPOINT ["bash", "/generate.sh"]
