CREATE DATABASE MyPastaDB;

\c MyPastaDB;

CREATE TABLE "Localizations" ("LocaleCode" varchar(5) PRIMARY KEY, "Content" TEXT);
CREATE TABLE "Users" ("Id" INT PRIMARY KEY, "Username" TEXT, "Password" TEXT);


INSERT INTO "Localizations" VALUES ('ru-RU', '<h1 class="display-2">Вермишелевый мир победил!</h1><br><p>Добро пожаловать в удивительный мир вкусных приключений – на макаронную фабрику "Мои макароны"! Наша фабрика – это не просто производство макарон, это настоящий храм гастрономического наслаждения, где каждая паста – это маленькое произведение искусства.</p><p>На "Моих макаронах" мы гордимся тем, что предлагаем высококачественные продукты, созданные с любовью и страстью к кулинарии. Наши макароны изготавливаются из отборных сортов пшеницы, выращенных с заботой о природе, без добавления искусственных красителей и консервантов.</p><p>Наш ассортимент порадует даже самых изысканных гурманов: от классических спагетти до уникальных форм и видов теста. Наши повара тщательно следят за каждым этапом производства, чтобы обеспечить идеальное сочетание текстуры и вкуса в каждой порции "Моих макарон".</p><p>Мы также гордимся тем, что поддерживаем экологически чистый подход в производстве, минимизируя отходы и используя устойчивые технологии. Мы уверены, что забота о природе дополняет заботу о вашем здоровье.</p><p>Присоединяйтесь к нам в этом увлекательном кулинарном путешествии, где каждый макарон – это не просто продукт, а история вкуса, традиций и качества. "Мои макароны" – это неотъемлемая часть вашего кулинарного опыта!</p>');
INSERT INTO "Localizations" VALUES ('en-US', '<h1 class="display-2">The pasta world has won!</h1><br><p>Welcome to the wonderful world of delicious adventures - to the pasta factory "My Pasta"! Our factory is not just a pasta production, it is a real temple of gastronomic pleasure, where each pasta is a small work of art.</p><p>At My Pasta we pride ourselves on offering high quality products created with love and passion for cooking. Our pasta is made from selected varieties of wheat, grown with care for nature, without the addition of artificial colors or preservatives.</p><p>Our assortment will delight even the most sophisticated gourmets: from classic spaghetti to unique shapes and types of dough. Our chefs carefully monitor every stage of production to ensure the perfect combination of texture and taste in each serving of My Pasta.</p><p>We are also proud to support an environmentally friendly approach to production, minimizing waste and using sustainable technologies. We are confident that caring for nature complements caring for your health.</p><p>Join us on this exciting culinary journey, where every pasta is not just a product, but a story of taste, tradition and quality. "My Pasta" is an integral part of your culinary experience!</p>');
INSERT INTO "Localizations" VALUES ('it-IT', '<h1 class="display-2">Il mondo della pasta ha vinto!</h1><br><p>Benvenuti nel meraviglioso mondo di deliziose avventure: nel pastificio "La mia pasta"! Il nostro pastificio non è solo una produzione di pasta, è un vero e proprio tempio del piacere gastronomico, dove ogni pasta è una piccola opera d''arte.</p><p>Noi di La mia pasta siamo orgogliosi di offrire prodotti di alta qualità creati con amore e passione per la cucina. La nostra pasta è prodotta con varietà selezionate di grano, coltivate nel rispetto della natura, senza l''aggiunta di coloranti o conservanti artificiali.</p><p>Il nostro assortimento delizierà anche i buongustai più sofisticati: dai classici spaghetti alle forme e tipologie di impasto uniche. I nostri chef monitorano attentamente ogni fase della produzione per garantire la perfetta combinazione di consistenza e gusto in ogni porzione di La mia pasta.</p><p>Siamo inoltre orgogliosi di sostenere un approccio rispettoso dell''ambiente alla produzione, riducendo al minimo gli sprechi e utilizzando tecnologie sostenibili. Siamo certi che la cura della natura sia complementare alla cura della salute.</p><p>Unisciti a noi in questo entusiasmante viaggio culinario, dove ogni pasta non è solo un prodotto, ma una storia di gusto, tradizione e qualità. "La mia pasta" è parte integrante della tua esperienza culinaria!</p>');
INSERT INTO "Localizations" VALUES ('fr-FR', '<h1 class="display-2">Le monde des pâtes a gagné!</h1><br><p>Bienvenue dans le monde merveilleux des délicieuses aventures - dans l''usine de pâtes "Mes pâtes"! Notre usine n''est pas seulement une production de pâtes, c''est un véritable temple du plaisir gastronomique, où chaque pâte est une petite œuvre d''art.</p><p>Chez Mes pâtes, nous sommes fiers d''offrir des produits de haute qualité créés avec amour et passion pour la cuisine. Nos pâtes sont fabriquées à partir de variétés de blé sélectionnées, cultivées dans le respect de la nature, sans ajout de colorants artificiels ni de conservateurs.</p><p>Notre assortiment ravira même les gourmets les plus sophistiqués: des spaghettis classiques aux formes et types de pâte uniques. Nos chefs surveillent attentivement chaque étape de la production pour garantir la combinaison parfaite de texture et de goût dans chaque portion de Mes pâtes.</p><p>Nous sommes également fiers de soutenir une approche de production respectueuse de l''environnement, en minimisant les déchets et en utilisant des technologies durables. Nous sommes convaincus que prendre soin de la nature complète le soin de votre santé.</p><p>Rejoignez-nous dans ce voyage culinaire passionnant, où chaque pâte n''est pas seulement un produit, mais une histoire de goût, de tradition et de qualité. "Mes pâtes" fait partie intégrante de votre expérience culinaire!</p>');
INSERT INTO "Localizations" VALUES ('zh-CN', '<h1 class="display-2">面食世界赢了!</h1><br><p>欢迎来到美味冒险的奇妙世界 - 意大利面工厂“我的面食”！ 我们的工厂不仅仅是生产面食，更是一座真正的美食殿堂，每一份面食都是一件小艺术品。</p><p>在 我的面食、我们为提供充满对烹饪的热爱和热情而创造的高品质产品而感到自豪。 我们的面食由精选小麦品种制成，在自然环境下种植，不添加人工色素或防腐剂。</p><p>我们的品种即使是最挑剔的美食家也会满意：从经典的意大利面到独特形状和类型的面团。 我们的厨师仔细监控生产的每个阶段，以确保每份“我的面食”的质地和味道完美结合。</p><p>我们还很自豪能够支持环保的生产方式、最大限度地减少浪费并使用可持续技术。 我们相信，关爱自然与关爱您的健康相辅相成。</p><p>加入我们这个激动人心的烹饪之旅，在这里，每一份面食不仅仅是一种产品，而是一个关于味道、传统和品质的故事。 “我的面食”是您烹饪体验中不可或缺的一部分！</p>');

INSERT INTO "Users" VALUES (1, 'pastalover', 'ZThmZWU3ZTctOTk5OS00NTRlLTk3NWQt');

CREATE ROLE readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;

CREATE USER pastapp_svc WITH PASSWORD 'MGY1MjIyMjUtNzRiZS00MTk4LWI0OTQt';
GRANT readaccess TO pastapp_svc;
